# _config.yml
title: "GJ's Site"
description: "Play more."
baseurl: ""  # 用户站点留空，项目站点填写仓库名
url: "https://hulandy.github.io"  # 你的域名

# 如果保持posts文件夹而不是_posts
collections:
  posts:
    output: true
    permalink: /posts/:path/
    # 或者使用 /:year/:month/:day/:title/
    
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      permalink: /:path/
      
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"

# 构建设置
markdown: kramdown
permalink: pretty

# 排除文件
exclude:
  - README.md
